
-- 新增房源
INSERT INTO building (`name`,
	`developer_id`,
	`build_status`,
	`handover_date`,
	`property_type`,
	`plan_area`,
	`total_household`,
	`decoration_en`,
	`decoration`,
	`age_limit`,
	`total_number`,
	`parking_space`,
	`housing_feature`,
	`mating`,
	`total_price`,
	`property_fee`,
	`payment`,
	`loans`,
	`gains`,
	`rental_income`,
	`main_pic`,
	`add_desc_en`,
	`add_desc`,
	`countries`,
	`province`,
	`city`,
	`region`,
	`address`,
	`longitude`,
	`latitude`,
	`project_feature_en`,
	`project_feature`,
	`project_book`,
	`status`,
	`subway_line`,
	`education`,
	`hospital`,
	`entertainment`,
	`shopping`,
	`restaurant`,
	`page_view`,
	`collection`,
	`readjust_collection`,
	`reservations`,
	`keyword`,
	`description`,
	`sort`,
	`is_delete`,
	`property_fee_type`,
	`thumb_pic`,
	`seo_title`,
	`seo_keyword`,
	`seo_description`,
	`recommend_en`,
	`recommend`,
	`label`,
	`market_book`,
	`market_book_click`,
	`market_time`,
	`project_book_click`,
	`contractor`,
	`agent_commision`,
	`sell_commision`,
	`market_commision`,
	`sales_policy`,
	`follow_person`,
	`remarks` )
SELECT
	`name`,
	`developer_id`,
	`build_status`,
	`handover_date`,
	`property_type`,
	`plan_area`,
	`total_household`,
	`decoration_en`,
	`decoration`,
	`age_limit`,
	`total_number`,
	`parking_space`,
	`housing_feature`,
	`mating`,
	`total_price`,
	`property_fee`,
	`payment`,
	`loans`,
	`gains`,
	`rental_income`,
	`main_pic`,
	`add_desc_en`,
	`add_desc`,
	`countries`,
	`province`,
	`city`,
	`region`,
	`address`,
	`longitude`,
	`latitude`,
	`project_feature_en`,
	`project_feature`,
	`project_book`,
	`status`,
	`subway_line`,
	`education`,
	`hospital`,
	`entertainment`,
	`shopping`,
	`restaurant`,
	`page_view`,
	`collection`,
	`readjust_collection`,
	`reservations`,
	`keyword`,
	`description`,
	`sort`,
	`is_delete`,
	`property_fee_type`,
	`thumb_pic`,
	`seo_title`,
	`seo_keyword`,
	`seo_description`,
	`recommend_en`,
	`recommend`,
	`label`,
	`market_book`,
	`market_book_click`,
	`market_time`,
	`project_book_click`,
	`contractor`,
	`agent_commision`,
	`sell_commision`,
	`market_commision`,
	`sales_policy`,
	`follow_person`,
	`remarks` 
FROM
	building 
WHERE
	id = 198 and is_delete = 0


select * from building where name like '%圣地湾-La Santir%'
select * from merchant m where m.name ='南洋房产' and is_delete = 0
select * from merchant where id = 4 and is_delete = 0
	
INSERT into merge_house_merchant 
	(`house_id`,
	`house_type`,
	`merchant_id`,
	`is_delete`,
	`create_time`,
	`update_time`)
	VALUE (345,"NEWHOUSE",4,0,NOW(),NOW())


select * from building where id = "345"

select * from merge_house_merchant where house_id = '345'
	